plugins {
	id 'java'
	id 'org.springframework.boot' version '3.2.1'
	id 'io.spring.dependency-management' version '1.1.4'
}

group = 'sporttagapp'
version = '0.0.1-SNAPSHOT'

java {
	sourceCompatibility = JavaVersion.VERSION_21
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	implementation group: 'org.apache.xmlgraphics', name: 'fop', version: '2.9'
	implementation group: 'net.sf.saxon', name: 'Saxon-HE', version: '12.4'
	//implementation group: 'org.apache.poi', name: 'poi', version: '5.2.5'
	implementation group: 'org.apache.poi', name: 'poi-ooxml', version: '5.2.5'
	// https://mvnrepository.com/artifact/com.google.code.gson/gson
	implementation group: 'com.google.code.gson', name: 'gson', version: '2.10.1'
}

tasks.named('test') {
	useJUnitPlatform()
}
